### ISSUE TITLE
Test al plugins in a .so?

### ISSUE THREAD

**Issue by magnetophon** [cth103/plugin-torture#3]
In https://github.com/cth103/plugin-torture/issues/2 you told me to remind you, so here we go!  :)

**Comment by cth103** [comment]
I'm being lazy here... what's a good .so to test with? :)

**Comment by magnetophon** [comment]
No problem :)

I haven't looked into this for a while now, but it seems [artyFX](https://github.com/openAVproductions/openAV-ArtyFX) has multiple plugins in a .so.
Another is [Calf](http://calf-studio-gear.org/).

Thanks!

**Comment by cth103** [comment]
Now done in git.  Let me know if you have problems...

**Comment by magnetophon** [comment]
Thanks!

I'm sorry I won't have time to test this month.

Remind me if I forget! ;)

**Comment by magnetophon** [comment]
Better late than never: It's working!
Thank you!
