### ISSUE TITLE
host doesn't support urid:map, giving up

### ISSUE THREAD

**Issue by magnetophon** [cth103/plugin-torture#4]
When I run:

```
plugin-torture --evil -d --lv2 --plugin /path/to/CharacterCompressor.lv2/manifest.ttl
```

on `https://github.com/magnetophon/CharacterCompressor`, I get:

```
LOG: Turning on denormal detection.
LOG: Running `CharacterCompressor' (/home/bart/faust/CharacterCompressor/CharacterCompressor.lv2/manifest.ttl)
http://faust-lv2.googlecode.com/CharacterCompressor: host doesn't support urid:map, giving up
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to instantiate LV2 plugin
[1]    308 abort       --evil -d --lv2 --plugin 
```

It probably comes from `https://github.com/alvasnaedis/faust/blob/master/architecture/lv2.cpp#L474`
(note: the above is an older version of the code, I just used this mirror for easy linking) 

Thanks!

**Comment by cth103** [comment]
This should be fixed by 023614efa0eab918955f6bed96e966f542cbcbf0 - let me know if not.

**Comment by magnetophon** [comment]
@cth103 Thanks for looking in to this.
Both my local tries and travis output [plugin-torture: Could not find LV2 plugin CharacterCompressorMono.lv2/manifest.ttl](https://travis-ci.org/magnetophon/CharacterCompressor/builds/147395003#L3236)

Somehow also older versions of plugin-torture say this, also for other plugins, so it looks like I'm doing it wrong, even though I'm using the same command as mentioned [above](https://github.com/cth103/plugin-torture/issues/4#issue-165546600).

**Comment by cth103** [comment]
At the moment the plugin under test has to be on LV2_PATH: is this the case for yours?

**Comment by magnetophon** [comment]
@cth103 Right, thanks.
I can confirm this issue closed now.  :smile:
